#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>

static void sig_int(int signo) {
	printf("stop pressing ctr-c!\n");
}
static void sig_term(int signo) {
	printf("stop trying to kill me!\n");
}
int main() {

	// SIGINT is generated by pressing ctr+c
	if (signal(SIGINT, &sig_int) == SIG_ERR) {
		perror("signal() failed");
		exit(1);
	}

	if (signal(SIGTERM, &sig_term) == SIG_ERR) {
		perror("signal() failed");
		exit(1);
	}

	int i = 0;

	for (;;) {
		printf("%d\n", i++);
		sleep(1);
	}
}
